# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
image: omalaspinas/palabos:latest

before_script:
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - ccache --set-config=compression=true
  - ccache --set-config=max_size=500M
    
cache:
    untracked: false
    key: "$CI_PROJECT_ID"
    paths:
        - ccache/
    
stages:
    - build_cmake
    - regression_tests
    - deploy

test:
    stage: regression_tests

    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Test
        - cmake --build . -j4
        - cmake --build . -- test

## Test compilation with CMake, everything in examples & utility directory
release_clang_serial:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MPI=OFF
        - cmake --build . -j4

release_clang_parallel:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MPI=ON
        - cmake --build . -j4

release_gcc_serial:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DENABLE_MPI=OFF
        - cmake --build . -j4
        
release_gcc_parallel:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DENABLE_MPI=ON
        - cmake --build . -j4

debug_clang_serial:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MPI=OFF
        - cmake --build . -j4

debug_clang_parallel:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MPI=ON
        - cmake --build . -j4

debug_gcc_serial:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ -DENABLE_MPI=OFF
        - cmake --build . -j4
        
debug_gcc_parallel:
    stage: build_cmake
    
    script: 
        - pwd
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ -DENABLE_MPI=ON
        - cmake --build . -j4
        
pages:
    stage: deploy
    script:
        - pwd
        - mkdir -p public/docs
        - doxygen Doxyfile
    artifacts:
        paths:
        - public
    only:
        - master


