# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
image: omalaspinas/palabos:latest
    
cache:
    untracked: false
    key: "$CI_PROJECT_ID"
    
stages:
    - build_cmake
    - deploy

## Test compilation with CMake, everything in examples & utility directory
cmake:
    stage: build_cmake

    only:
        - master
    
    script: 
        - pwd
        - cd build
        - cmake ..
        - make -j4

pages:
    stage: deploy
    script:
        - pwd
        - mkdir -p public/docs
        - doxygen Doxyfile
    artifacts:
        paths:
        - public
    only:
        - master


