version: 1.0.{build}
branches:
  only:
  - appveyor

image: 
  - Previous Visual Studio 2019
  - macOS

install:
- pwsh: >-
    if ($isWindows) {
      
    } else {
      brew install open-mpi
    }
    
build_script:
- pwsh: >-
    if ($isWindows) {
        
    } else {
        cd build
    }

    cmake .. -DBUILD_HDF5=OFF

    cmake --build . -j4
test: off
deploy: off